<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'ZipStream\\' => array($vendorDir . '/maennchen/zipstream-php/src'),
    'Symfony\\Component\\Finder\\' => array($vendorDir . '/symfony/finder'),
    'Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-message/src', $vendorDir . '/psr/http-factory/src'),
    'Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'PhpOffice\\PhpSpreadsheet\\' => array($vendorDir . '/phpoffice/phpspreadsheet/src/PhpSpreadsheet'),
    'MyCLabs\\Enum\\' => array($vendorDir . '/myclabs/php-enum/src'),
    'Michael\\Uts\\' => array($baseDir . '/src'),
    'Matrix\\' => array($vendorDir . '/markbaker/matrix/classes/src'),
    'Gregwar\\' => array($vendorDir . '/gregwar/captcha/src/Gregwar'),
    'Complex\\' => array($vendorDir . '/markbaker/complex/classes/src'),
);
